const fa = (value) => String(value).replace(/\d/g, (digit) => "۰۱۲۳۴۵۶۷۸۹"[digit]);
const set = (categoryId, targets) => ({ schemaVersion: 1, categoryId, targets });
const watts = (categoryId, name, values, extra = {}) => set(categoryId, values.map((watt) => ({ variantId: `${watt}w`, label: `${name} ${fa(watt)} وات`, attributes: { watt, ...extra } })));
const amperes = (categoryId, name, values, extra = {}) => set(categoryId, values.map((ampere) => ({ variantId: `${ampere}a`, label: `${name} ${fa(ampere)} آمپر`, attributes: { ampere, ...extra } })));
const models = (categoryId, values) => set(categoryId, values.map(([variantId, label, attributes]) => ({ variantId, label, attributes })));

export const DEFAULT_MARKET_REFERENCE_TARGETS = [
	watts("economy-bulbs", "لامپ LED اقتصادی", [9, 12, 15, 20, 30, 50]),
	models("led-bulbs", [["9w-a-bulb-e27", "لامپ LED حبابی ۹ وات پایه E27", { watt: 9, formFactor: "a-bulb", socketType: "E27" }], ["12w-a-bulb-e27", "لامپ LED حبابی ۱۲ وات پایه E27", { watt: 12, formFactor: "a-bulb", socketType: "E27" }], ["15w-a-bulb-e27", "لامپ LED حبابی ۱۵ وات پایه E27", { watt: 15, formFactor: "a-bulb", socketType: "E27" }], ["20w-a-bulb-e27", "لامپ LED حبابی ۲۰ وات پایه E27", { watt: 20, formFactor: "a-bulb", socketType: "E27" }], ["30w-cylindrical-e27", "لامپ LED استوانه‌ای ۳۰ وات پایه E27", { watt: 30, formFactor: "cylindrical", socketType: "E27" }], ["40w-cylindrical-e27", "لامپ LED استوانه‌ای ۴۰ وات پایه E27", { watt: 40, formFactor: "cylindrical", socketType: "E27" }], ["50w-cylindrical-e27", "لامپ LED استوانه‌ای ۵۰ وات پایه E27", { watt: 50, formFactor: "cylindrical", socketType: "E27" }]]),
	models("filament-bulbs", [4, 6, 8, 10].map((watt) => [`${watt}w-a60-e27`, `لامپ فیلامنتی حبابی A60 ${fa(watt)} وات پایه E27`, { watt, shape: "a60", socketType: "E27" }])),
	models("candle-bulbs", [5, 7, 9].map((watt) => [`${watt}w-candle-e14`, `لامپ شمعی LED ${fa(watt)} وات پایه E14`, { watt, shape: "candle", socketType: "E14" }])),
	models("halogen-bulbs", [5, 7, 9, 12].map((watt) => [`${watt}w-gu10`, `لامپ هالوژنی LED ${fa(watt)} وات پایه GU10`, { watt, socketType: "GU10" }])),
	set("led-tube-lights", [{ variantId: "9w-60cm", label: "لامپ تیوب LED ۹ وات ۶۰ سانتی‌متر", attributes: { watt: 9, lengthCm: 60 } }, { variantId: "18w-120cm", label: "لامپ تیوب LED ۱۸ وات ۱۲۰ سانتی‌متر", attributes: { watt: 18, lengthCm: 120 } }, { variantId: "20w-120cm", label: "لامپ تیوب LED ۲۰ وات ۱۲۰ سانتی‌متر", attributes: { watt: 20, lengthCm: 120 } }]),
	set("led-strips", [["12v-single-color-5m", "ریسه نواری LED تک‌رنگ ۱۲ ولت کلاف ۵ متری", { voltage: 12, colorMode: "single-color", lengthM: 5 }], ["24v-single-color-5m", "ریسه نواری LED تک‌رنگ ۲۴ ولت کلاف ۵ متری", { voltage: 24, colorMode: "single-color", lengthM: 5 }], ["220v-single-color-1m", "ریسه LED تک‌رنگ ۲۲۰ ولت یک متری", { voltage: 220, colorMode: "single-color", lengthM: 1 }]].map(([variantId, label, attributes]) => ({ variantId, label, attributes }))), watts("led-modules", "ماژول LED", [1.5, 3, 6, 12]), watts("led-chips", "چیپ LED", [10, 20, 30, 50, 100]),
	set("led-drivers", [[7, 12], [12, 18], [18, 36], [36, 50]].map(([minWatt, maxWatt]) => ({ variantId: `${minWatt}-${maxWatt}w-300ma`, label: `درایور LED جریان ثابت ${fa(minWatt)} تا ${fa(maxWatt)} وات ۳۰۰ میلی‌آمپر`, attributes: { minWatt, maxWatt, outputCurrentMa: 300 } }))),
	set("led-power-supplies", [60, 100, 150, 200, 300].map((watt) => ({ variantId: `${watt}w-12v`, label: `منبع تغذیه LED ${fa(watt)} وات ۱۲ ولت`, attributes: { watt, voltage: 12 } }))), watts("ceiling-panels", "پنل سقفی LED", [12, 18, 24, 36, 48], { shape: "round" }), watts("downlights", "چراغ دان‌لایت", [7, 12, 18, 24]), watts("spotlights", "چراغ اسپات", [7, 12, 20, 30]), watts("projectors", "پروژکتور LED", [30, 50, 100, 150, 200]), watts("street-lights", "چراغ خیابانی", [50, 100, 150, 200]),
	models("wall-lights", [["outdoor-led-12w-ip54", "چراغ دیواری LED فضای باز ۱۲ وات IP54", { watt: 12, ipRating: "IP54", environment: "outdoor" }], ["outdoor-led-20w-ip65", "چراغ دیواری LED فضای باز ۲۰ وات IP65", { watt: 20, ipRating: "IP65", environment: "outdoor" }], ["outdoor-e27", "چراغ دیواری فضای باز تک‌شعله با سرپیچ E27", { socketType: "E27", environment: "outdoor" }]]),
	models("ceiling-lights", [["round-18w", "چراغ سقفی روکار LED گرد ۱۸ وات", { watt: 18, shape: "round", mountType: "surface" }], ["round-24w", "چراغ سقفی روکار LED گرد ۲۴ وات", { watt: 24, shape: "round", mountType: "surface" }], ["round-36w", "چراغ سقفی روکار LED گرد ۳۶ وات", { watt: 36, shape: "round", mountType: "surface" }], ["square-24w", "چراغ سقفی روکار LED مربع ۲۴ وات", { watt: 24, shape: "square", mountType: "surface" }]]),
	models("emergency-lights", [["30-led", "چراغ اضطراری شارژی ۳۰ لامپ", { ledCount: 30, rechargeable: true }], ["36-led", "چراغ اضطراری شارژی ۳۶ لامپ", { ledCount: 36, rechargeable: true }], ["56-led", "چراغ اضطراری شارژی ۵۶ لامپ", { ledCount: 56, rechargeable: true }], ["60-led", "چراغ اضطراری شارژی ۶۰ لامپ", { ledCount: 60, rechargeable: true }], ["40cm-linear", "چراغ اضطراری خطی شارژی ۴۰ سانتی‌متر", { lengthCm: 40, rechargeable: true }]]),
	models("sensor-lights", [["ceiling-pir", "چراغ سقفی سنسوردار PIR", { sensorType: "PIR", mountType: "ceiling" }], ["wall-pir", "چراغ دیواری سنسوردار PIR", { sensorType: "PIR", mountType: "wall" }], ["outdoor-photocell", "چراغ فضای باز فتوسل‌دار", { sensorType: "photocell", environment: "outdoor" }]]),
	set("cabinet-lights", [30, 60, 90, 120].map((lengthCm) => ({ variantId: `${lengthCm}cm`, label: `چراغ کابینتی ${fa(lengthCm)} سانتی‌متر`, attributes: { lengthCm } }))), set("linear-lights", [60, 100, 120, 150].map((lengthCm) => ({ variantId: `${lengthCm}cm`, label: `چراغ خطی ${fa(lengthCm)} سانتی‌متر`, attributes: { lengthCm } }))), watts("track-lights", "چراغ ریلی", [10, 20, 30, 40]),
	models("garden-lights", [["wall", "چراغ باغی دیواری", { mountType: "wall" }], ["spike", "چراغ باغی نیزه‌ای", { mountType: "spike" }], ["short-post", "چراغ باغی پایه‌کوتاه", { mountType: "short_post" }], ["buried", "چراغ باغی دفنی", { mountType: "buried" }]]), models("led-controllers", [["single-12v", "کنترلر ریسه تک‌رنگ ۱۲ ولت", { voltage: 12, colorMode: "single" }], ["rgb-12v", "کنترلر RGB دوازده ولت", { voltage: 12, colorMode: "RGB" }], ["rgb-24v", "کنترلر RGB بیست‌وچهار ولت", { voltage: 24, colorMode: "RGB" }], ["rgbw-12v", "کنترلر RGBW دوازده ولت", { voltage: 12, colorMode: "RGBW" }]]),
	models("led-strip-accessories", [["connector", "رابط ریسه LED", { accessoryType: "connector" }], ["socket", "سوکت ریسه LED", { accessoryType: "socket" }], ["profile-1m", "پروفیل آلومینیومی ریسه یک متری", { accessoryType: "profile", lengthCm: 100 }], ["profile-cap", "درپوش پروفیل ریسه", { accessoryType: "profile_cap" }], ["rectifier-220v", "یکسوساز ریسه ۲۲۰ ولت", { accessoryType: "rectifier", voltage: 220 }]]),
	models("wall-switches", [["1gang", "کلید یک‌پل", { gangCount: 1 }], ["2gang", "کلید دوپل", { gangCount: 2 }], ["3gang", "کلید سه‌پل", { gangCount: 3 }]]), models("wall-sockets", [["standard", "پریز برق معمولی", { socketType: "standard" }], ["grounded", "پریز برق ارت‌دار", { socketType: "grounded" }], ["telephone", "پریز تلفن", { socketType: "telephone" }], ["network", "پریز شبکه", { socketType: "network" }]]),
	models("dimmers", [["rotary-led", "دیمر گردان LED", { mountType: "rotary" }], ["touch-led", "دیمر لمسی LED", { mountType: "touch" }], ["200w", "دیمر LED تا ۲۰۰ وات", { maxWatt: 200 }], ["400w", "دیمر LED تا ۴۰۰ وات", { maxWatt: 400 }]]), models("smart-switches", [1, 2, 3, 4].map((gangCount) => [`wifi-${gangCount}gang`, `کلید هوشمند Wi-Fi ${fa(gangCount)} پل`, { gangCount, protocol: "Wi-Fi" }])),
	set("industrial-plugs", [[16, 3], [16, 5], [32, 3], [32, 5], [63, 5]].map(([ampere, poles]) => ({ variantId: `${ampere}a-${poles}p`, label: `دوشاخه صنعتی ${fa(ampere)} آمپر ${fa(poles)} پل`, attributes: { ampere, poles } }))), set("industrial-sockets", [[16, 3], [16, 5], [32, 3], [32, 5], [63, 5]].map(([ampere, poles]) => ({ variantId: `${ampere}a-${poles}p`, label: `پریز صنعتی ${fa(ampere)} آمپر ${fa(poles)} پل`, attributes: { ampere, poles } }))),
	set("miniature-circuit-breakers", [6, 10, 16, 20, 25, 32, 40, 63].map((ampere) => ({ variantId: `1p-c${ampere}-6ka`, label: `کلید مینیاتوری تک‌پل ${fa(ampere)} آمپر تیپ C با قدرت قطع ۶ کیلوآمپر`, attributes: { ampere, poles: 1, curve: "C", breakingCapacityKA: 6 } }))),
	set("residual-current-devices", [[2, 25], [2, 40], [2, 63], [4, 40], [4, 63]].map(([poles, ampere]) => ({ variantId: `${poles}p-${ampere}a-30ma`, label: `محافظ جان ${fa(poles)} پل ${fa(ampere)} آمپر ۳۰ میلی‌آمپر`, attributes: { ampere, poles, residualCurrentMa: 30 } }))), set("molded-case-circuit-breakers", [63, 100, 160, 250, 400].map((ampere) => ({ variantId: `3p-${ampere}a`, label: `کلید اتوماتیک سه‌پل ${fa(ampere)} آمپر`, attributes: { ampere, poles: 3 } }))), amperes("fuse-holders", "پایه فیوز", [10, 16, 25, 32, 63]),
	set("distribution-boxes", [4, 6, 8, 12, 18, 24].map((moduleCount) => ({ variantId: `${moduleCount}module`, label: `جعبه فیوز ${fa(moduleCount)} ماژول`, attributes: { moduleCount } }))), models("distribution-panels", [["surface-12module", "تابلو برق روکار ۱۲ ماژول", { moduleCount: 12, mountType: "surface" }], ["surface-18module", "تابلو برق روکار ۱۸ ماژول", { moduleCount: 18, mountType: "surface" }], ["surface-24module", "تابلو برق روکار ۲۴ ماژول", { moduleCount: 24, mountType: "surface" }], ["flush-12module", "تابلو برق توکار ۱۲ ماژول", { moduleCount: 12, mountType: "flush" }], ["flush-24module", "تابلو برق توکار ۲۴ ماژول", { moduleCount: 24, mountType: "flush" }]]), amperes("contactors", "کنتاکتور", [9, 12, 18, 25, 32, 40]),
	set("electrical-relays", [[5, 12], [5, 24], [10, 12], [10, 24], [10, 220]].map(([ampere, voltage]) => ({ variantId: `${ampere}a-${voltage}v`, label: `رله برق ${fa(ampere)} آمپر ${fa(voltage)} ولت`, attributes: { ampere, voltage } }))), models("time-switches", [["analog-daily", "تایمر برق آنالوگ روزانه", { model: "analog", schedule: "daily" }], ["digital-daily", "تایمر برق دیجیتال روزانه", { model: "digital", schedule: "daily" }], ["digital-weekly", "تایمر برق دیجیتال هفتگی", { model: "digital", schedule: "weekly" }]]),
	set("voltage-protectors", [[25, 1], [40, 1], [63, 1], [40, 3], [63, 3]].map(([ampere, poles]) => ({ variantId: `${ampere}a-${poles}p`, label: `محافظ ولتاژ ${fa(ampere)} آمپر ${fa(poles)} پل`, attributes: { ampere, poles } }))),
	set("building-wire", [1.5, 2.5, 4, 6, 10].map((crossSectionMm2) => ({ variantId: `${crossSectionMm2}mm2`, label: `سیم ساختمان ${fa(crossSectionMm2)} میلی‌متر مربع`, attributes: { crossSectionMm2 } }))), set("flexible-cable", [[2, 1.5], [2, 2.5], [3, 1.5], [3, 2.5], [3, 4], [4, 4]].map(([cores, crossSectionMm2]) => ({ variantId: `${cores}x${crossSectionMm2}`, label: `کابل افشان ${fa(cores)} رشته ${fa(crossSectionMm2)} میلی‌متر مربع`, attributes: { cores, crossSectionMm2 } }))), set("power-cable", [[2, 2.5], [3, 2.5], [3, 4], [3, 6], [4, 6], [4, 10]].map(([cores, crossSectionMm2]) => ({ variantId: `${cores}x${crossSectionMm2}`, label: `کابل برق ${fa(cores)} رشته ${fa(crossSectionMm2)} میلی‌متر مربع`, attributes: { cores, crossSectionMm2 } }))),
	models("coaxial-cable", [["rg59", "کابل کواکسیال RG59", { model: "RG59" }], ["rg6", "کابل کواکسیال RG6", { model: "RG6" }], ["rg11", "کابل کواکسیال RG11", { model: "RG11" }]]), set("conduit", [13.5, 16, 21, 29].map((diameterMm) => ({ variantId: `${diameterMm}mm`, label: `لوله برق ${fa(diameterMm)} میلی‌متر`, attributes: { diameterMm } }))), set("flexible-conduit", [11, 13, 16, 21, 25].map((diameterMm) => ({ variantId: `${diameterMm}mm`, label: `لوله خرطومی ${fa(diameterMm)} میلی‌متر`, attributes: { diameterMm } }))),
	set("trunking", [[10, 10], [20, 10], [20, 20], [30, 30], [40, 40], [60, 40]].map(([widthMm, heightMm]) => ({ variantId: `${widthMm}x${heightMm}mm`, label: `داکت برق ${fa(widthMm)} در ${fa(heightMm)} میلی‌متر`, attributes: { widthMm, heightMm } }))), set("junction-boxes", [10, 15, 20, 25].map((size) => ({ variantId: `${size}x${size}cm`, label: `جعبه تقسیم ${fa(size)} در ${fa(size)} سانتی‌متر`, attributes: { widthCm: size, heightCm: size } }))),
];
