import { MarketReferenceValidationError } from "./marketReferenceService.js";
import { validateResearchTargets } from "./marketReferenceTargetsService.js";

const SCHEMA_VERSION = 1;
const VARIANT_SCHEMAS = new Set(["wattage", "ampere", "breaker_model", "cable_size", "model", "size", "generic"]);
function error(message) { return new MarketReferenceValidationError(message); }
function plain(value) { return Boolean(value) && typeof value === "object" && !Array.isArray(value) && (Object.getPrototypeOf(value) === Object.prototype || Object.getPrototypeOf(value) === null); }
function exact(value, keys, label) { if (!plain(value) || Object.keys(value).some((key) => !keys.includes(key)) || keys.some((key) => !(key in value))) throw error(`${label} is invalid.`); }
function text(value, label) { if (typeof value !== "string" || !value.trim()) throw error(`${label} must be a non-empty string.`); }
function url(value) { if (typeof value !== "string") throw error("Raw Search Result url must be an absolute HTTP or HTTPS URL."); let parsed; try { parsed = new URL(value); } catch { throw error("Raw Search Result url must be an absolute HTTP or HTTPS URL."); } if (!["http:", "https:"].includes(parsed.protocol)) throw error("Raw Search Result url must be an absolute HTTP or HTTPS URL."); }

export function validateSearchQuery(query) { exact(query, ["schemaVersion", "queryId", "categoryId", "variantId", "query"], "Search Query"); if (query.schemaVersion !== SCHEMA_VERSION) throw error("Search Query schemaVersion must be 1."); for (const key of ["queryId", "categoryId", "variantId", "query"]) text(query[key], `Search Query ${key}`); return query; }
export function validateRawSearchResult(raw) { exact(raw, ["schemaVersion", "queryId", "results"], "Raw Search Result"); if (raw.schemaVersion !== SCHEMA_VERSION) throw error("Raw Search Result schemaVersion must be 1."); text(raw.queryId, "Raw Search Result queryId"); if (!Array.isArray(raw.results)) throw error("Raw Search Result results must be an array."); for (const result of raw.results) { exact(result, ["sourceId", "url", "title", "snippet"], "Raw Search Result item"); text(result.sourceId, "Raw Search Result sourceId"); url(result.url); if (typeof result.title !== "string" || typeof result.snippet !== "string") throw error("Raw Search Result title and snippet must be strings."); } return raw; }
function validateCategory(category) { exact(category, ["id", "title", "variantSchema", "enabled"], "Research category"); text(category.id, "Research category id"); text(category.title, "Research category title"); if (!VARIANT_SCHEMAS.has(category.variantSchema) || category.enabled !== true) throw error("Research category is invalid or disabled."); }
function compatible(schema, attributes) { const required = schema === "wattage" ? "watt" : schema === "ampere" ? "ampere" : null; if (required && (typeof attributes[required] !== "number" || !Number.isFinite(attributes[required]))) throw error(`Research Target attributes must include a finite numeric ${required}.`); }
export function buildResearchQueries({ category, targets }) { validateCategory(category); const validTargets = validateResearchTargets(targets); if (category.id !== validTargets.categoryId) throw error("Research category id must match Research Targets categoryId."); return validTargets.targets.map((target) => { compatible(category.variantSchema, target.attributes); return validateSearchQuery({ schemaVersion: 1, queryId: `${category.id}:${target.variantId}:price`, categoryId: category.id, variantId: target.variantId, query: `${category.title} ${target.label} قیمت تومان` }); }); }
