import { describe, expect, it } from "vitest";
import { MarketReferenceValidationError } from "../src/marketReference/marketReferenceService.js";
import { buildResearchQueries, validateRawSearchResult, validateSearchQuery } from "../src/marketReference/marketReferenceResearchProvider.js";
function category(overrides = {}) { return { id: "led-bulbs", title: "لامپ LED", variantSchema: "wattage", enabled: true, ...overrides }; }
function targets(overrides = {}) { return { schemaVersion: 1, categoryId: "led-bulbs", targets: [{ variantId: "20w", label: "20 وات", attributes: { watt: 20 } }], ...overrides }; }
describe("market reference research provider contracts", () => {
	it("builds one canonical Persian query per target in target order without mutation", () => { const input = { category: category(), targets: targets({ targets: [{ variantId: "20w", label: "20 وات", attributes: { watt: 20 } }, { variantId: "9w", label: "9 وات", attributes: { watt: 9 } }] }) }; const original = structuredClone(input); expect(buildResearchQueries(input)).toEqual([{ schemaVersion: 1, queryId: "led-bulbs:20w:price", categoryId: "led-bulbs", variantId: "20w", query: "لامپ LED 20 وات قیمت تومان" }, { schemaVersion: 1, queryId: "led-bulbs:9w:price", categoryId: "led-bulbs", variantId: "9w", query: "لامپ LED 9 وات قیمت تومان" }]); expect(input).toEqual(original); });
	it("enforces category, target, schema compatibility, and strict Search Query validation", () => { expect(() => buildResearchQueries({ category: category(), targets: targets({ categoryId: "other" }) })).toThrow(MarketReferenceValidationError); expect(() => buildResearchQueries({ category: category({ variantSchema: "bad" }), targets: targets() })).toThrow(MarketReferenceValidationError); expect(() => buildResearchQueries({ category: category(), targets: targets({ targets: [{ variantId: "x", label: "x", attributes: {} }] }) })).toThrow(MarketReferenceValidationError); expect(() => buildResearchQueries({ category: category({ variantSchema: "ampere" }), targets: targets({ targets: [{ variantId: "x", label: "x", attributes: { watt: 1 } }] }) })).toThrow(MarketReferenceValidationError); expect(() => validateSearchQuery({ schemaVersion: 1, queryId: "q", categoryId: "c", variantId: "v", query: "x", extra: true })).toThrow(MarketReferenceValidationError); });
	it("validates provider-independent raw results; empty results and empty title/snippet are valid", () => { expect(validateRawSearchResult({ schemaVersion: 1, queryId: "q", results: [] })).toBeTruthy(); expect(validateRawSearchResult({ schemaVersion: 1, queryId: "q", results: [{ sourceId: "s", url: "http://example.com/x", title: "", snippet: "" }, { sourceId: "s2", url: "https://example.com/y", title: "t", snippet: "n" }] })).toBeTruthy(); expect(() => validateRawSearchResult({ schemaVersion: 1, queryId: "q", results: [{ sourceId: "s", url: "/x", title: "", snippet: "" }] })).toThrow(MarketReferenceValidationError); expect(() => validateRawSearchResult({ schemaVersion: 1, queryId: "q", results: [], extra: true })).toThrow(MarketReferenceValidationError); });
});
