import { describe, expect, it, vi } from "vitest";
import { SerperSearchProviderError, searchWithSerper } from "../src/marketReference/serperSearchProvider.js";
const query = { schemaVersion: 1, queryId: "led-bulbs:20w:price", categoryId: "led-bulbs", variantId: "20w", query: "لامپ LED 20 وات قیمت تومان" };
function response(body, status = 200) { return new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json" } }); }
describe("Serper search provider", () => {
	it("sends exactly one canonical Serper request and maps normalized organic results", async () => { const fetchImpl = vi.fn(async () => response({ organic: [{ title: "first", link: "https://example.com/a?x=1#fragment", snippet: "s", position: 1 }, { title: "duplicate", link: "https://example.com/a?x=1#other" }, { link: "bad" }, { link: "http://example.org/p" }] })); const result = await searchWithSerper({ searchQuery: query, apiKey: "test-secret", fetchImpl }); expect(fetchImpl).toHaveBeenCalledTimes(1); const [endpoint, init] = fetchImpl.mock.calls[0]; expect(endpoint).toBe("https://google.serper.dev/search"); expect(init).toMatchObject({ method: "POST", headers: { "X-API-KEY": "test-secret", "Content-Type": "application/json" } }); expect(JSON.parse(init.body)).toEqual({ q: query.query, gl: "ir", hl: "fa", num: 10 }); expect(result).toEqual({ schemaVersion: 1, queryId: query.queryId, results: [{ sourceId: "https://example.com/a?x=1", url: "https://example.com/a?x=1", title: "first", snippet: "s" }, { sourceId: "http://example.org/p", url: "http://example.org/p", title: "", snippet: "" }] }); });
	it("validates input and key before fetch and accepts missing or empty organic arrays", async () => { const fetchImpl = vi.fn(async () => response({})); await expect(searchWithSerper({ searchQuery: query, apiKey: "", fetchImpl })).rejects.toBeInstanceOf(SerperSearchProviderError); await expect(searchWithSerper({ searchQuery: { ...query, query: " " }, apiKey: "x", fetchImpl })).rejects.toThrow(); expect(fetchImpl).not.toHaveBeenCalled(); expect(await searchWithSerper({ searchQuery: query, apiKey: "x", fetchImpl })).toEqual({ schemaVersion: 1, queryId: query.queryId, results: [] }); });
	it("returns controlled errors without exposing API keys", async () => { for (const fetchImpl of [vi.fn(async () => response({}, 401)), vi.fn(async () => response({}, 429)), vi.fn(async () => response({}, 500)), vi.fn(async () => { throw new Error("network"); }), vi.fn(async () => ({ ok: true, json: async () => { throw new Error("bad json"); } }))]) { await expect(searchWithSerper({ searchQuery: query, apiKey: "secret-value", fetchImpl })).rejects.toBeInstanceOf(SerperSearchProviderError); try { await searchWithSerper({ searchQuery: query, apiKey: "secret-value", fetchImpl }); } catch (error) { expect(error.message).not.toContain("secret-value"); } } });
});
